{
 "title": "Monitoreo de Métricas (Prometheus) - DemoApp",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "_controller",
    "label": "Controlador",
    "query": "label_values(http_requests_received_total{app=\"base-talentos-dev\"}, controller)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latencia Promedio por Endpoint (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (code, method, controller, action, endpoint) (rate(http_request_duration_seconds_sum{app=\"base-talentos-dev\", controller=~\"$_controller\"}[5m]))\n/\n(sum by (code, method, controller, action, endpoint) (rate(http_requests_received_total{app=\"base-talentos-dev\", controller=~\"$_controller\"}[5m])) + 0.000000001)",
     "legendFormat": "{{controller}} - {{action}} ({{code}})"
    }
   ]
  },
  {
   "title": "Solicitudes HTTP por Segundo (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code, method, controller, action, endpoint) (rate(http_requests_received_total{app=\"base-talentos-dev\", controller=~\"$_controller\"}[5m]))",
     "legendFormat": "{{controller}} - {{action}} ({{code}})"
    }
   ]
  },
  {
   "title": "Errores HTTP por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code, method, controller, action, endpoint) (rate(http_requests_received_total{app=\"base-talentos-dev\", code=~\"4..|5..\", controller=~\"$_controller\"}[5m]))",
     "legendFormat": "{{controller}} - {{action}} (Error: {{code}})"
    }
   ]
  }
 ]
}